version: "3.3"
services:
    nodeserver:
        build:
            context: ./
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8000:8000"
        links:
            - nodeserver
